name: danra
zarrs:
  state:
    - path: "https://mllam-test-data.s3.eu-north-1.amazonaws.com/single_levels.zarr"
      dims:
        time: time
        level: null
        x: x
        y: y
        grid: null
      lat_lon_names:
        lon: lon
        lat: lat
    - path: "https://mllam-test-data.s3.eu-north-1.amazonaws.com/height_levels.zarr"
      dims:
        time: time
        level: altitude
        x: x
        y: y
        grid: null
      lat_lon_names:
        lon: lon
        lat: lat
  static:
    path: "https://mllam-test-data.s3.eu-north-1.amazonaws.com/single_levels.zarr"
    dims:
      level: null
      x: x
      y: y
      grid: null
    lat_lon_names:
      lon: lon
      lat: lat
  forcing:
    path: "https://mllam-test-data.s3.eu-north-1.amazonaws.com/single_levels.zarr"
    dims:
      time: time
      level: null
      x: x
      y: y
      grid: null
    lat_lon_names:
      lon: lon
      lat: lat
state:
  surface_vars:
    - u10m
    - v10m
    - t2m
  surface_units:
    - m/s
    - m/s
    - K
  atmosphere_vars:
    - u
    - v
    - t
  atmosphere_units:
    - m/s
    - m/s
    - K
  levels:
    - 100
static:
  surface_vars:
    - pres0m # just as a technical test
  atmosphere_vars: null
  levels: null
forcing:
  surface_vars:
    - cape_column # just as a technical test
  atmosphere_vars: null
  levels: null
  window: 3 # Number of time steps to use for forcing (odd)
grid_shape_state:
  x: 582
  y: 390
splits:
  train:
    start: 1990-09-01T00
    end: 1990-09-11T00
  val:
    start: 1990-09-11T03
    end: 1990-09-13T09
  test:
    start: 1990-09-11T03
    end: 1990-09-13T09
projection:
  class: LambertConformal # Name of class in cartopy.crs
  kwargs:
    central_longitude: 6.22
    central_latitude: 56.0
    standard_parallels: [47.6, 64.4]
normalization:
  zarr: normalization.zarr
  vars:
    data_mean: data_mean
    data_std: data_std
    forcing_mean: forcing_mean
    forcing_std: forcing_std
    boundary_mean: boundary_mean
    boundary_std: boundary_std
    diff_mean: diff_mean
    diff_std: diff_std
